/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTradesRouteImport } from './routes/api/trades'
import { Route as ApiSosovalueRouteImport } from './routes/api/sosovalue'
import { Route as ApiSodexPrepareRouteImport } from './routes/api/sodex-prepare'
import { Route as ApiSodexPositionsRouteImport } from './routes/api/sodex-positions'
import { Route as ApiSodexOrderRouteImport } from './routes/api/sodex-order'
import { Route as ApiSodexBalanceRouteImport } from './routes/api/sodex-balance'
import { Route as ApiSignalsRouteImport } from './routes/api/signals'
import { Route as ApiPriceRouteImport } from './routes/api/price'
import { Route as ApiNewsRouteImport } from './routes/api/news'
import { Route as ApiAnalyzeRouteImport } from './routes/api/analyze'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTradesRoute = ApiTradesRouteImport.update({
  id: '/api/trades',
  path: '/api/trades',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSosovalueRoute = ApiSosovalueRouteImport.update({
  id: '/api/sosovalue',
  path: '/api/sosovalue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSodexPrepareRoute = ApiSodexPrepareRouteImport.update({
  id: '/api/sodex-prepare',
  path: '/api/sodex-prepare',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSodexPositionsRoute = ApiSodexPositionsRouteImport.update({
  id: '/api/sodex-positions',
  path: '/api/sodex-positions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSodexOrderRoute = ApiSodexOrderRouteImport.update({
  id: '/api/sodex-order',
  path: '/api/sodex-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSodexBalanceRoute = ApiSodexBalanceRouteImport.update({
  id: '/api/sodex-balance',
  path: '/api/sodex-balance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSignalsRoute = ApiSignalsRouteImport.update({
  id: '/api/signals',
  path: '/api/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPriceRoute = ApiPriceRouteImport.update({
  id: '/api/price',
  path: '/api/price',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsRoute = ApiNewsRouteImport.update({
  id: '/api/news',
  path: '/api/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeRoute = ApiAnalyzeRouteImport.update({
  id: '/api/analyze',
  path: '/api/analyze',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/news': typeof ApiNewsRoute
  '/api/price': typeof ApiPriceRoute
  '/api/signals': typeof ApiSignalsRoute
  '/api/sodex-balance': typeof ApiSodexBalanceRoute
  '/api/sodex-order': typeof ApiSodexOrderRoute
  '/api/sodex-positions': typeof ApiSodexPositionsRoute
  '/api/sodex-prepare': typeof ApiSodexPrepareRoute
  '/api/sosovalue': typeof ApiSosovalueRoute
  '/api/trades': typeof ApiTradesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/news': typeof ApiNewsRoute
  '/api/price': typeof ApiPriceRoute
  '/api/signals': typeof ApiSignalsRoute
  '/api/sodex-balance': typeof ApiSodexBalanceRoute
  '/api/sodex-order': typeof ApiSodexOrderRoute
  '/api/sodex-positions': typeof ApiSodexPositionsRoute
  '/api/sodex-prepare': typeof ApiSodexPrepareRoute
  '/api/sosovalue': typeof ApiSosovalueRoute
  '/api/trades': typeof ApiTradesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/news': typeof ApiNewsRoute
  '/api/price': typeof ApiPriceRoute
  '/api/signals': typeof ApiSignalsRoute
  '/api/sodex-balance': typeof ApiSodexBalanceRoute
  '/api/sodex-order': typeof ApiSodexOrderRoute
  '/api/sodex-positions': typeof ApiSodexPositionsRoute
  '/api/sodex-prepare': typeof ApiSodexPrepareRoute
  '/api/sosovalue': typeof ApiSosovalueRoute
  '/api/trades': typeof ApiTradesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/api/analyze'
    | '/api/news'
    | '/api/price'
    | '/api/signals'
    | '/api/sodex-balance'
    | '/api/sodex-order'
    | '/api/sodex-positions'
    | '/api/sodex-prepare'
    | '/api/sosovalue'
    | '/api/trades'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/api/analyze'
    | '/api/news'
    | '/api/price'
    | '/api/signals'
    | '/api/sodex-balance'
    | '/api/sodex-order'
    | '/api/sodex-positions'
    | '/api/sodex-prepare'
    | '/api/sosovalue'
    | '/api/trades'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/api/analyze'
    | '/api/news'
    | '/api/price'
    | '/api/signals'
    | '/api/sodex-balance'
    | '/api/sodex-order'
    | '/api/sodex-positions'
    | '/api/sodex-prepare'
    | '/api/sosovalue'
    | '/api/trades'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  ApiAnalyzeRoute: typeof ApiAnalyzeRoute
  ApiNewsRoute: typeof ApiNewsRoute
  ApiPriceRoute: typeof ApiPriceRoute
  ApiSignalsRoute: typeof ApiSignalsRoute
  ApiSodexBalanceRoute: typeof ApiSodexBalanceRoute
  ApiSodexOrderRoute: typeof ApiSodexOrderRoute
  ApiSodexPositionsRoute: typeof ApiSodexPositionsRoute
  ApiSodexPrepareRoute: typeof ApiSodexPrepareRoute
  ApiSosovalueRoute: typeof ApiSosovalueRoute
  ApiTradesRoute: typeof ApiTradesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trades': {
      id: '/api/trades'
      path: '/api/trades'
      fullPath: '/api/trades'
      preLoaderRoute: typeof ApiTradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sosovalue': {
      id: '/api/sosovalue'
      path: '/api/sosovalue'
      fullPath: '/api/sosovalue'
      preLoaderRoute: typeof ApiSosovalueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sodex-prepare': {
      id: '/api/sodex-prepare'
      path: '/api/sodex-prepare'
      fullPath: '/api/sodex-prepare'
      preLoaderRoute: typeof ApiSodexPrepareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sodex-positions': {
      id: '/api/sodex-positions'
      path: '/api/sodex-positions'
      fullPath: '/api/sodex-positions'
      preLoaderRoute: typeof ApiSodexPositionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sodex-order': {
      id: '/api/sodex-order'
      path: '/api/sodex-order'
      fullPath: '/api/sodex-order'
      preLoaderRoute: typeof ApiSodexOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sodex-balance': {
      id: '/api/sodex-balance'
      path: '/api/sodex-balance'
      fullPath: '/api/sodex-balance'
      preLoaderRoute: typeof ApiSodexBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/signals': {
      id: '/api/signals'
      path: '/api/signals'
      fullPath: '/api/signals'
      preLoaderRoute: typeof ApiSignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/price': {
      id: '/api/price'
      path: '/api/price'
      fullPath: '/api/price'
      preLoaderRoute: typeof ApiPriceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/news': {
      id: '/api/news'
      path: '/api/news'
      fullPath: '/api/news'
      preLoaderRoute: typeof ApiNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze': {
      id: '/api/analyze'
      path: '/api/analyze'
      fullPath: '/api/analyze'
      preLoaderRoute: typeof ApiAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  ApiAnalyzeRoute: ApiAnalyzeRoute,
  ApiNewsRoute: ApiNewsRoute,
  ApiPriceRoute: ApiPriceRoute,
  ApiSignalsRoute: ApiSignalsRoute,
  ApiSodexBalanceRoute: ApiSodexBalanceRoute,
  ApiSodexOrderRoute: ApiSodexOrderRoute,
  ApiSodexPositionsRoute: ApiSodexPositionsRoute,
  ApiSodexPrepareRoute: ApiSodexPrepareRoute,
  ApiSosovalueRoute: ApiSosovalueRoute,
  ApiTradesRoute: ApiTradesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
